# Generated by Django 2.2.6 on 2019-10-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('fecha_Registro', models.DateField()),
                ('AreaEspecialidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='respuesta',
            name='aplausos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Registro', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('aplausos', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Doctor')),
            ],
        ),
    ]
