# Generated by Django 2.2.6 on 2019-10-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20191026_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('caracteristicas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectividad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_Registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Medicamento')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Articulo')),
                ('sintomas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Sintoma')),
            ],
        ),
    ]
